### PR TITLE
Apply Validation only if configure option is not provided. Fixes #8

### LINKED ISSUE #8: Make .source .files optional when config file specified
When the configuration file is specified, wouldn't it be better to assume that input sources are handled? Otherwise one has to explicitly specify `files` or `source` only to be overridden by the ones in `config`.

### PR DESCRIPTION
**Pull request by kp96**
Fix for  #8

### CODE REVIEW

**Comment by 75lb** [comment]
thanks, i will look at this tonight or tomorrow.

**Comment by kp96** [comment]
Sure, I would be happy update the validation to check for `input` in `conf.json` as well. Let me know your thoughts. Thanks.

**Comment by 75lb** [comment]
yes, please check for input files in the config file too please 👍

**Comment by brutalcrozt** [comment]
update guys?

**Comment by kp96** [comment]
I'm sorry I couldn't find time to do it. Feel free to take over.

**Pull request closed without merging**
